services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      # - ./app:/app
      - .env:/app/.env
    # environment:
    # - DATABASE_URL=mysql+pymysql://user:password@mysql/dbname
    # - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mysql
      - redis

  tests:
    container_name: tests
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: pytest --maxfail=1 --disable-warnings -q
    volumes:
      - ./backend/app:/app/app
      - ./backend/test:/app/test
      - .env:/app/.env
    depends_on:
      - backend
      - mysql
      - redis
    profiles:
      - test

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
