[project]
name = "testtask-c32"
version = "0.1.0"
authors = [
    {name = "Alexksandrov Dmtirii", email = "Adsis369@gmail.com"},
]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
